name: Config Server CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    uses: alexisrodriguezcs/ecommerce-infra/.github/workflows/ci-template.yml@main
    with:
      service_name: config-server
      sonar_organization: ar-ecommerce-platform
      enable_config_server: false
    secrets:
      REPORTS_TRIGGER_TOKEN: ${{ secrets.REPORTS_TRIGGER_TOKEN }}
      OWASP_API_KEY: ${{ secrets.OWASP_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}