name: CI for Config Server

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build, Test, and Report
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      image_name: ${{ steps.meta.outputs.image_name }}
      sha_tag: ${{ steps.meta.outputs.sha_tag }}
      latest_tag: ${{ steps.meta.outputs.latest_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set image metadata
        id: meta
        run: |
          echo "image_name=ghcr.io/alexisrodriguezcs/ecommerce-config-server" >> $GITHUB_OUTPUT
          echo "sha_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "latest_tag=latest" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: |
          docker build -t ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.sha_tag }} \
                       -t ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.latest_tag }} .

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Deploy test report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/tests/test
          destination_dir: test-report
          keep_files: true

      - name: Print report URL
        run: |
          echo "View the test report at: https://alexisrodriguezcs.github.io/test-report/index.html"\

  publish-image:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=${{ needs.build-and-test.outputs.image_name }}
          SHA_TAG=${{ needs.build-and-test.outputs.sha_tag }}
          LATEST_TAG=${{ needs.build-and-test.outputs.latest_tag }}
          
          docker push $IMAGE_NAME:$SHA_TAG
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker push $IMAGE_NAME:$LATEST_TAG
          fi